server:
  port: 8082

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/spring-microservice-basic-boilerplate/config-server
          clone-on-start: true